@echo off

set KDEDIRS=E:\kde4-msvc
set PATH=%PATH%;%KDEDIRS%\bin;%KDEDIRS%\plugins
set KDE4_INSTALL_DIR=%KDEDIRS%
set KDEDIRS=%KDEDIRS%
set KDE4_LIB_DIRS=%KDEDIRS%
set KDEROOT=%KDEDIRS%
set QTMAKESPEC=%KDEDIRS%\mkspecs\win32-g++
set QT_PLUGIN_PATH=%KDEDIRS%\plugins
set QTDIR=%KDEDIRS%
set QT_INSTALL_DIR=%KDEDIRS%


rem clean up CMake cache
del /F CMakeCache.txt

rem configure CMake env.
#cmake -G "MinGW Makefiles" . -DCMAKE_INCLUDE_PATH=%KDEDIRS%/include -DCMAKE_LIBRARY_PATH=%KDEDIRS%/lib -DCMAKE_INSTALL_PREFIX=%KDE4_INSTALL_DIR% 
#cmake -G "Visual Studio 9 2008" . -DEXPAT_LIBRARY=%KDEDIRS%/lib/libexpat.lib -DCMAKE_INCLUDE_PATH=%KDEDIRS%/include -DCMAKE_LIBRARY_PATH=%KDEDIRS%/lib -DCMAKE_INSTALL_PREFIX=%KDE4_INSTALL_DIR% 
cmake -G "NMake Makefiles" . -DEXPAT_LIBRARY=%KDEDIRS%/lib/libexpat.lib -DCMAKE_INCLUDE_PATH=%KDEDIRS%/include -DCMAKE_LIBRARY_PATH=%KDEDIRS%/lib -DCMAKE_INSTALL_PREFIX=%KDE4_INSTALL_DIR% 

 