@ECHO OFF

REM Adjust there the right path to KDE4 install directory.
SET KDE4_INSTALL_DIR=E:\kde4-mingw

SET PATH=%PATH%;%KDE4_INSTALL_DIR%\bin;%KDE4_INSTALL_DIR%\plugins
SET KDEDIRS=%KDE4_INSTALL_DIR%
SET KDE4_LIB_DIRS=%KDE4_INSTALL_DIR%
SET KDEROOT=%KDE4_INSTALL_DIR%
SET QTMAKESPEC=%KDE4_INSTALL_DIR%\mkspecs\win32-g++
SET QT_PLUGIN_PATH=%KDE4_INSTALL_DIR%\plugins
SET QTDIR=%KDE4_INSTALL_DIR%
SET QT_INSTALL_DIR=%KDE4_INSTALL_DIR%

REM Clean-up CMake cache file.
DEL /F CMakeCache.txt

REM configure CMake env with right compiler. Uncoment the right line.

REM MinGW : gcc for Windows.
cmake -G "MinGW Makefiles" . -DCMAKE_INCLUDE_PATH=%KDE4_INSTALL_DIR%/include -DCMAKE_LIBRARY_PATH=%KDE4_INSTALL_DIR%/lib -DCMAKE_INSTALL_PREFIX=%KDE4_INSTALL_DIR%

REM Microsoft Visual C++ IDE.
REM cmake -G "Visual Studio 9 2008" . -DEXPAT_LIBRARY=%KDE4_INSTALL_DIR%/lib/libexpat.lib -DCMAKE_INCLUDE_PATH=%KDE4_INSTALL_DIR%/include -DCMAKE_LIBRARY_PATH=%KDE4_INSTALL_DIR%/lib -DCMAKE_INSTALL_PREFIX=%KDE4_INSTALL_DIR%

REM Microsoft Visual C++ command line compiler.
REM cmake -G "NMake Makefiles" . -DEXPAT_LIBRARY=%KDE4_INSTALL_DIR%/lib/libexpat.lib -DCMAKE_INCLUDE_PATH=%KDE4_INSTALL_DIR%/include -DCMAKE_LIBRARY_PATH=%KDE4_INSTALL_DIR%/lib -DCMAKE_INSTALL_PREFIX=%KDE4_INSTALL_DIR%

