#!/usr/bin/perl

# Copyright (c) 2008-2018, Gilles Caulier, <caulier dot gilles at gmail dot com>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

system("perl ./gits populate");

if ( $? > 0 )
{
    print "$ : Failed to populate gits repositories, aborting.\n";
    exit (-1);
}

exit (0);
