[Desktop Action digiKam Download]
Exec=@digikamhelperdir@/digikam-camera storage %u
Icon=digikam
Name=Download Photos with digiKam
Name[ca]=Descàrrega de fotos amb el digiKam
Name[cs]=Stáhnout fotografie pomocí digiKamu
Name[da]=Download fotografier med digiKam
Name[de]=Fotos mit digiKam herunterladen
Name[el]=Λήψη φωτογραφιών με το digiKam
Name[et]=Fotode allalaadimine digiKamiga
Name[fi]=Lataa valokuvat digiKamilla
Name[fr]=Télécharger des photos avec Digikam
Name[gl]=Descargar Fotos con digiKam
Name[is]=Hala niður myndum með digiKam
Name[it]=Scarica foto con digiKam
Name[ja]=digiKam で写真をダウンロード
Name[km]=ទាញយក​រូបថត​ដោយ digiKam
Name[lt]=Atsisiųsti nuotraukas su digiKam
Name[lv]=Ielādēt fotogrāfijas ar digiKam
Name[nb]=Last ned fotografier med digiKam
Name[nds]=Fotos mit digiKam daalladen
Name[nl]=Foto's met digiKam downloaden
Name[pa]=ਡਿਜਿਕੈਮ ਨਾਲ ਫੋਟੋ ਡਾਊਨਲੋਡ ਕਰੋ
Name[pl]=Pobierz zdjęcia za pomocą digiKam
Name[pt]=Obter Fotos com o digiKam
Name[pt_BR]=Baixar as fotos com o digiKam
Name[ro]=Descărcere fotografii cu digiKam
Name[sv]=Ladda ner foton med Digikam
Name[th]=ดาวน์โหลดภาพถ่ายด้วย digiKam
Name[tr]=Fotoğrafları DigiKam ile İndir
Name[uk]=Завантажити фотографії програмою digiKam
Name[x-test]=xxDownload Photos with digiKamxx
Name[zh_CN]=用 digiKam 下载照片

[Desktop Entry]
Encoding=UTF-8
Actions=digiKam Download;
Type=Service
ServiceTypes=KonqPopupMenu/Plugin,media/removable_mounted,media/camera_mounted
