#!/bin/sh

action="$1"; shift;

case "$action" in
detect)
	cmdoption=--detect-camera
	dcopcall=detectCamera
	;;
storage)
	cmdoption=--download-from
	dcopcall=downloadFrom
	;;
*)
	echo "${0##*/}: wrong action.  Usage"
	echo "	${0##*/}  detect 	# for gphoto2 supported cameras"
	echo "	${0##*/}  storage <url>	# for usbdisk or directries with images"
	exit 1
	;;
esac

for app in `dcop`; do
	case "$app" in
	    digikam-*)
		echo "recycling running $app: $dcopcall $@"
		exec dcop "$app" camera  "$dcopcall" "$@"
	    ;;
	esac
done;
echo "starting digikam with $cmdoption $@"
exec digikam  "$cmdoption" "$@"
